#!/usr/bin/env python3
"""
Add capital cities to the countries.csv file
"""

import pandas as pd

# Read the existing CSV file
df = pd.read_csv('/Users/eshvarov/Github/potato-analytics/data/countries.csv')

# Dictionary mapping country names to their capitals
capitals = {
    'Afghanistan': 'Kabul',
    'Albania': 'Tirana',
    'Algeria': 'Algiers',
    'American Samoa': 'Pago Pago',
    'Andorra': 'Andorra la Vella',
    'Angola': 'Luanda',
    'Anguilla': 'The Valley',
    'Antarctica': None,  # No capital
    'Antigua and Barbuda': "Saint John's",
    'Argentina': 'Buenos Aires',
    'Armenia': 'Yerevan',
    'Aruba': 'Oranjestad',
    'Australia': 'Canberra',
    'Austria': 'Vienna',
    'Azerbaijan': 'Baku',
    'Bahamas': 'Nassau',
    'Bahrain': 'Manama',
    'Bangladesh': 'Dhaka',
    'Barbados': 'Bridgetown',
    'Belarus': 'Minsk',
    'Belgium': 'Brussels',
    'Belize': 'Belmopan',
    'Benin': 'Porto-Novo',
    'Bermuda': 'Hamilton',
    'Bhutan': 'Thimphu',
    'Bolivia, Plurinational State of': 'Sucre',
    'Bonaire, Sint Eustatius and Saba': 'Kralendijk',
    'Bosnia and Herzegovina': 'Sarajevo',
    'Botswana': 'Gaborone',
    'Bouvet Island': None,  # Uninhabited
    'Brazil': 'Brasília',
    'British Indian Ocean Territory': None,  # No permanent population
    'Brunei Darussalam': 'Bandar Seri Begawan',
    'Bulgaria': 'Sofia',
    'Burkina Faso': 'Ouagadougou',
    'Burundi': 'Gitega',
    'Cambodia': 'Phnom Penh',
    'Cameroon': 'Yaoundé',
    'Canada': 'Ottawa',
    'Cape Verde': 'Praia',
    'Cayman Islands': 'George Town',
    'Central African Republic': 'Bangui',
    'Chad': "N'Djamena",
    'Chile': 'Santiago',
    'China': 'Beijing',
    'Christmas Island': 'Flying Fish Cove',
    'Cocos (Keeling) Islands': 'West Island',
    'Colombia': 'Bogotá',
    'Comoros': 'Moroni',
    'Congo': 'Brazzaville',
    'Congo, the Democratic Republic of the': 'Kinshasa',
    'Cook Islands': 'Avarua',
    'Costa Rica': 'San José',
    'Croatia': 'Zagreb',
    'Cuba': 'Havana',
    'Curaçao': 'Willemstad',
    'Cyprus': 'Nicosia',
    'Czech Republic': 'Prague',
    "Côte d'Ivoire": 'Yamoussoukro',
    'Denmark': 'Copenhagen',
    'Djibouti': 'Djibouti',
    'Dominica': 'Roseau',
    'Dominican Republic': 'Santo Domingo',
    'Ecuador': 'Quito',
    'Egypt': 'Cairo',
    'El Salvador': 'San Salvador',
    'Equatorial Guinea': 'Malabo',
    'Eritrea': 'Asmara',
    'Estonia': 'Tallinn',
    'Eswatini': 'Mbabane',
    'Ethiopia': 'Addis Ababa',
    'Falkland Islands (Malvinas)': 'Stanley',
    'Faroe Islands': 'Tórshavn',
    'Fiji': 'Suva',
    'Finland': 'Helsinki',
    'France': 'Paris',
    'French Guiana': 'Cayenne',
    'French Polynesia': 'Papeete',
    'French Southern Territories': None,  # No permanent population
    'Gabon': 'Libreville',
    'Gambia': 'Banjul',
    'Georgia': 'Tbilisi',
    'Germany': 'Berlin',
    'Ghana': 'Accra',
    'Gibraltar': 'Gibraltar',
    'Greece': 'Athens',
    'Greenland': 'Nuuk',
    'Grenada': "Saint George's",
    'Guadeloupe': 'Basse-Terre',
    'Guam': 'Hagåtña',
    'Guatemala': 'Guatemala City',
    'Guernsey': 'Saint Peter Port',
    'Guinea': 'Conakry',
    'Guinea-Bissau': 'Bissau',
    'Guyana': 'Georgetown',
    'Haiti': 'Port-au-Prince',
    'Heard Island and McDonald Islands': None,  # Uninhabited
    'Holy See (Vatican City State)': 'Vatican City',
    'Honduras': 'Tegucigalpa',
    'Hong Kong': 'Hong Kong',
    'Hungary': 'Budapest',
    'Iceland': 'Reykjavík',
    'India': 'New Delhi',
    'Indonesia': 'Jakarta',
    'Iran, Islamic Republic of': 'Tehran',
    'Iraq': 'Baghdad',
    'Ireland': 'Dublin',
    'Isle of Man': 'Douglas',
    'Israel': 'Jerusalem',
    'Italy': 'Rome',
    'Jamaica': 'Kingston',
    'Japan': 'Tokyo',
    'Jersey': 'Saint Helier',
    'Jordan': 'Amman',
    'Kazakhstan': 'Nur-Sultan',
    'Kenya': 'Nairobi',
    'Kiribati': 'Tarawa',
    'Korea, Democratic People\'s Republic of': 'Pyongyang',
    'Korea, Republic of': 'Seoul',
    'Kuwait': 'Kuwait City',
    'Kyrgyzstan': 'Bishkek',
    'Lao People\'s Democratic Republic': 'Vientiane',
    'Latvia': 'Riga',
    'Lebanon': 'Beirut',
    'Lesotho': 'Maseru',
    'Liberia': 'Monrovia',
    'Libya': 'Tripoli',
    'Liechtenstein': 'Vaduz',
    'Lithuania': 'Vilnius',
    'Luxembourg': 'Luxembourg',
    'Macao': 'Macao',
    'Macedonia, the Former Yugoslav Republic of': 'Skopje',
    'Madagascar': 'Antananarivo',
    'Malawi': 'Lilongwe',
    'Malaysia': 'Kuala Lumpur',
    'Maldives': 'Malé',
    'Mali': 'Bamako',
    'Malta': 'Valletta',
    'Marshall Islands': 'Majuro',
    'Martinique': 'Fort-de-France',
    'Mauritania': 'Nouakchott',
    'Mauritius': 'Port Louis',
    'Mayotte': 'Mamoudzou',
    'Mexico': 'Mexico City',
    'Micronesia, Federated States of': 'Palikir',
    'Moldova, Republic of': 'Chișinău',
    'Monaco': 'Monaco',
    'Mongolia': 'Ulaanbaatar',
    'Montenegro': 'Podgorica',
    'Montserrat': 'Plymouth',
    'Morocco': 'Rabat',
    'Mozambique': 'Maputo',
    'Myanmar': 'Naypyidaw',
    'Namibia': 'Windhoek',
    'Nauru': 'Yaren',
    'Nepal': 'Kathmandu',
    'Netherlands': 'Amsterdam',
    'New Caledonia': 'Nouméa',
    'New Zealand': 'Wellington',
    'Nicaragua': 'Managua',
    'Niger': 'Niamey',
    'Nigeria': 'Abuja',
    'Niue': 'Alofi',
    'Norfolk Island': 'Kingston',
    'Northern Mariana Islands': 'Saipan',
    'Norway': 'Oslo',
    'Oman': 'Muscat',
    'Pakistan': 'Islamabad',
    'Palau': 'Ngerulmud',
    'Palestine, State of': 'East Jerusalem',
    'Panama': 'Panama City',
    'Papua New Guinea': 'Port Moresby',
    'Paraguay': 'Asunción',
    'Peru': 'Lima',
    'Philippines': 'Manila',
    'Pitcairn': 'Adamstown',
    'Poland': 'Warsaw',
    'Portugal': 'Lisbon',
    'Puerto Rico': 'San Juan',
    'Qatar': 'Doha',
    'Romania': 'Bucharest',
    'Russian Federation': 'Moscow',
    'Rwanda': 'Kigali',
    'Réunion': 'Saint-Denis',
    'Saint Barthélemy': 'Gustavia',
    'Saint Helena, Ascension and Tristan da Cunha': 'Jamestown',
    'Saint Kitts and Nevis': 'Basseterre',
    'Saint Lucia': 'Castries',
    'Saint Martin (French part)': 'Marigot',
    'Saint Pierre and Miquelon': 'Saint-Pierre',
    'Saint Vincent and the Grenadines': 'Kingstown',
    'Samoa': 'Apia',
    'San Marino': 'San Marino',
    'Sao Tome and Principe': 'São Tomé',
    'Saudi Arabia': 'Riyadh',
    'Senegal': 'Dakar',
    'Serbia': 'Belgrade',
    'Seychelles': 'Victoria',
    'Sierra Leone': 'Freetown',
    'Singapore': 'Singapore',
    'Sint Maarten (Dutch part)': 'Philipsburg',
    'Slovakia': 'Bratislava',
    'Slovenia': 'Ljubljana',
    'Solomon Islands': 'Honiara',
    'Somalia': 'Mogadishu',
    'South Africa': 'Cape Town',
    'South Georgia and the South Sandwich Islands': None,  # No permanent population
    'South Sudan': 'Juba',
    'Spain': 'Madrid',
    'Sri Lanka': 'Colombo',
    'Sudan': 'Khartoum',
    'Suriname': 'Paramaribo',
    'Svalbard and Jan Mayen': 'Longyearbyen',
    'Sweden': 'Stockholm',
    'Switzerland': 'Bern',
    'Syrian Arab Republic': 'Damascus',
    'Taiwan, Province of China': 'Taipei',
    'Tajikistan': 'Dushanbe',
    'Tanzania, United Republic of': 'Dodoma',
    'Thailand': 'Bangkok',
    'Timor-Leste': 'Dili',
    'Togo': 'Lomé',
    'Tokelau': None,  # No capital
    'Tonga': "Nuku'alofa",
    'Trinidad and Tobago': 'Port of Spain',
    'Tunisia': 'Tunis',
    'Turkey': 'Ankara',
    'Turkmenistan': 'Ashgabat',
    'Turks and Caicos Islands': 'Cockburn Town',
    'Tuvalu': 'Funafuti',
    'Uganda': 'Kampala',
    'Ukraine': 'Kyiv',
    'United Arab Emirates': 'Abu Dhabi',
    'United Kingdom': 'London',
    'United States': 'Washington, D.C.',
    'United States Minor Outlying Islands': None,  # No permanent population
    'Uruguay': 'Montevideo',
    'Uzbekistan': 'Tashkent',
    'Vanuatu': 'Port Vila',
    'Venezuela, Bolivarian Republic of': 'Caracas',
    'Viet Nam': 'Hanoi',
    'Virgin Islands, British': 'Road Town',
    'Virgin Islands, U.S.': 'Charlotte Amalie',
    'Wallis and Futuna': 'Mata-Utu',
    'Western Sahara': 'El Aaiún',
    'Yemen': "Sana'a",
    'Zambia': 'Lusaka',
    'Zimbabwe': 'Harare',
    'Åland Islands': 'Mariehamn'
}

# Add the Capital column
df['Capital'] = df['Name'].map(capitals)

# Save the updated CSV
output_file = '/Users/eshvarov/Github/potato-analytics/data/countries.csv'
df.to_csv(output_file, index=False)

print(f"Updated countries.csv with Capital column")
print(f"Added capitals for {len(df)} countries/territories")
print("\nSample of updated data:")
print(df.head(10))

print(f"\nCountries without capitals (territories/uninhabited areas):")
no_capital = df[df['Capital'].isna()]
print(f"Found {len(no_capital)} territories without capitals:")
for _, row in no_capital.iterrows():
    print(f"  {row['Name']}")
