name: Cloud Run Deploy

on:
  push:
    branches:
    - master
    - main
  workflow_dispatch:

jobs:
  deploy:
    uses: intersystems-community/demo-deployment/.github/workflows/deployment.yml@master
    with:
      # Replace the name: parameter below to have your application deployed at
      # https://lovable-backend.demo.community.intersystems.com/
      name: potato-analytics
      memory: 1G
    secrets:
      # Do not forget to add Secret in GitHub Repoository Settings with name SERVICE_ACCOUNT_KEY
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      CUSTOM_VARS_LIST: "ISC_CPF_MERGE_FILE: /usr/irissys/merge.cpf"
